.TH CPMLS 1 "November 22, 1997" "CP/M tools" "User commands"
.SH NAME \"{{{roff}}}\"{{{
cpmls \- list sorted contents of directory
.\"}}}
.SH SYNOPSIS \"{{{
.ad l
.B cpmls
.RB [ \-d | \-D | \-l [ \-c ]]
.RB [ \-f
.IR format ]
.I image
.RI [ file-pattern "...]"
.ad b
.\"}}}
.SH DESCRIPTION \"{{{
\fBcpmls\fP lists the sorted contents of the directory.
.\"}}}
.SH OPTIONS \"{{{
.IP "\fB\-f\fP \fIformat\fP"
Use the given CP/M disk \fIformat\fP instead of the default format.
.IP \fB\-d\fP
Old CP/M 2.2 dir output.
.IP \fB\-D\fP
P2DOS 2.3 ddir-like output.
.IP \fB\-l\fP
Long UNIX-style directory listing including size, time stamp and user number.
.IP \fB\-c\fP
Output the creation time, not the modification time.
.\"}}}
.SH "RETURN VALUE" \"{{{
Upon successful completion, exit code 0 is returned.
.\"}}}
.SH ERRORS \"{{{
Any errors are indicated by exit code 1.
.\"}}}
.SH FILES \"{{{
diskdef	CP/M disk format definitions
.\"}}}
.SH AUTHOR \"{{{
Michael Haardt (michael@moria.de)
.\"}}}
.SH "SEE ALSO" \"{{{
.IR cpmcp (1),
.IR cpm (5)
.\"}}}
